# https://taskfile.dev

version: '3'

vars:
  BINARY_NAME: notarry
  OPERATING_SYSTEMS: |
    windows
    linux
    darwin
    
dotenv: ['.env']

tasks:
  default:
    cmds:
      - task: test
  
  build:darwin:amd64:
    cmds: 
      - GOARCH=amd64 GOOS=darwin go build -o build/{{$.BINARY_NAME}}-darwin-amd64 main.go

  build:darwin:arm64:
    cmds: 
      - GOARCH=arm64 GOOS=darwin go build -o build/{{$.BINARY_NAME}}-darwin-arm64 main.go

  build:darwin:
    cmds:
      - task: build:darwin:amd64
      - task: build:darwin:arm64

  build:linux:amd64:
    cmds: 
      - GOARCH=amd64 GOOS=linux go build -o build/{{$.BINARY_NAME}}-linux-amd64 main.go
  
  build:linux:arm64:
    cmds: 
      - GOARCH=arm64 GOOS=linux go build -o build/{{$.BINARY_NAME}}-linux-arm64 main.go

  build:linux:
    cmds:
      - task: build:linux:amd64
      - task: build:linux:arm64

  build:windows:
    cmds: 
      - GOARCH=amd64 GOOS=windows go build -o build/{{$.BINARY_NAME}}-windows.exe main.go
  
  build:
    deps:
      - clean
    cmds:
      - task: build:darwin
      - task: build:linux
      - task: build:windows

  clean:
    cmds:
      - go clean
      - rm build/*

  test:
    cmds:
      - go test ./...

  test:e2e:
    cmds:
      - task: test:grab
      - task: test:download
      - task: test:upgrade
      - task: test:delete

  test:test:
    dir: test/e2e
    cmds:
      - |
        set -a 
        source test.env
        set +a
        go run ../../main.go

  test:grab:
    dir: test/e2e
    cmds:
      - |
        set -a 
        source grab.env
        set +a
        go run ../../main.go

  test:delete:
    dir: test/e2e
    cmds:
      - |
        set -a 
        source delete.env
        set +a
        go run ../../main.go
  
  test:download:
    dir: test/e2e
    cmds:
      - |
        set -a 
        source download.env
        set +a
        go run ../../main.go
  
  test:upgrade:
    dir: test/e2e
    cmds:
      - |
        set -a 
        source upgrade.env
        set +a
        go run ../../main.go

  test:webhook:
    cmds:
      - go run main.go webhook
